site_name: Apex
site_description: >-
  Official documentation for Apex project.
site_author: FT
site_url: https://fabetabilo.github.io/apex-docs/

repo_name: apex-docs
repo_url: https://github.com/fabetabilo/apex-docs

copyright: >
  Apex is an independent learning project. Not affiliated with the brands, products or external apps mentioned.

theme:
  name: material
  language: en

  palette:
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  font:
    text: IBM Plex Sans
    code: JetBrains Mono

  favicon: assets/favicon.png
  logo: assets/sml.png
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - glightbox

extra_css:
  - css/style.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fabetabilo/apex-docs

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - tables
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 3

nav:
  - Home: index.md
  - Datalogger:
      - Installation: datalogger/installation.md
      - Getting Started: datalogger/getting-started.md
      - Features: datalogger/features.md
